# Generated by Django 3.2.6 on 2021-09-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210817_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='antistresstoy',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='antistresstoy',
            name='image3',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='plastictoy',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='plastictoy',
            name='image3',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='plushtoy',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='plushtoy',
            name='image3',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='antistresstoy',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='antistresstoy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='plastictoy',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='plastictoy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена'),
        ),
    ]
