# Generated by Django 3.2.6 on 2021-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210905_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='antistresstoy',
            name='note',
            field=models.CharField(max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='plastictoy',
            name='note',
            field=models.CharField(max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='plushtoy',
            name='note',
            field=models.CharField(max_length=255, null=True, verbose_name='Примечание'),
        ),
    ]
