# Generated by Django 3.2.6 on 2021-09-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210905_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antistresstoy',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='antistresstoy',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='antistresstoy',
            name='note',
        ),
        migrations.RemoveField(
            model_name='plastictoy',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='plastictoy',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='plastictoy',
            name='note',
        ),
        migrations.RemoveField(
            model_name='plushtoy',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='plushtoy',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='plushtoy',
            name='note',
        ),
        migrations.AlterField(
            model_name='antistresstoy',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='plastictoy',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
