# Generated by Django 3.2.6 on 2021-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210907_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antistresstoy',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='plastictoy',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='plushtoy',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
